In [1]:
import pandas as pd
import numpy as np

In [2]:
fatigue_df = pd.read_csv("../data/processed/피로도.csv")

In [3]:
fatigue_df

,Name,Year,Team,Date,Role,ERA,WHIP,IP,NP,R,...,Other,누적_IP,FIP,GSv2,avg_GSv2,delta_GSv2,Total_IP,직구_피안타율,직구_구사율,변화구_구사율
0,고영표,2021,KT,2021-04-07,SP,1.50,0.83,6.000000,88,1,...,NaN,6.000000,4.003,72,72.961538,-0.961538,166.666667,0.254000,28.0,72.0
1,고영표,2021,KT,2021-04-13,SP,4.50,1.17,6.000000,95,3,...,NaN,12.000000,1.337,72,72.961538,-0.961538,166.666667,0.254000,28.0,72.0
2,고영표,2021,KT,2021-04-18,SP,3.00,0.83,6.000000,91,2,...,NaN,18.000000,3.670,72,72.961538,-0.961538,166.666667,0.254000,28.0,72.0
3,고영표,2021,KT,2021-04-24,SP,4.50,1.83,6.000000,86,3,...,NaN,24.000000,2.503,64,72.961538,-8.961538,166.666667,0.254000,28.0,72.0
4,고영표,2021,KT,2021-04-30,SP,3.86,1.14,7.000000,97,3,...,NaN,31.000000,3.599,76,72.961538,3.038462,166.666667,0.254000,28.0,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18050,후라도,2024,키움,2024-08-25,SP,2.57,0.43,7.000000,101,2,...,NaN,165.333333,4.023,80,71.766667,8.233333,190.333333,0.291414,53.6,46.4
18051,후라도,2024,키움,2024-09-03,SP,5.79,1.93,4.666667,103,7,...,NaN,170.000000,5.095,59,71.766667,-12.766667,190.333333,0.291414,53.6,46.4
18052,후라도,2024,키움,2024-09-08,SP,3.68,0.95,7.333333,97,4,...,NaN,177.333333,2.075,78,71.766667,6.233333,190.333333,0.291414,53.6,46.4
18053,후라도,2024,키움,2024-09-14,SP,1.29,1.00,7.000000,90,1,...,NaN,184.333333,4.309,75,71.766667,3.233333,190.333333,0.291414,53.6,46.4
18054,후라도,2024,키움,2024-09-22,SP,9.00,1.00,6.000000,88,6,...,NaN,190.333333,9.333,61,71.766667,-10.766667,190.333333,0.291414,53.6,46.4

In [4]:
fatigue_df.isnull().sum()

Name                      0
Year                      0
Team                      0
Date                      0
Role                      0
ERA                       0
WHIP                    527
IP                        0
NP                        0
R                         0
ER                        0
H                         0
HR                        0
SO                        0
BB                        0
HB                        0
Venue                     0
Temp                      0
연투 여부                     0
휴식일 수                     0
연투일                       0
2023WBC                   0
2021올림픽                   0
2023아시안게임                 0
2023아시아프로야구챔피언십           0
2023 아시아 야구 선수권 대회        0
2019프리미어12                0
PS_KS                     0
PS_PO                     0
PS_SP                     0
PS_V                      0
PS_WC                     0
Height                    0
Weight                    0
Age                       0
총이동거리                     0
전체구속                      5
2Seam                 15805
4Seam                  1421
Cutter                17493
Curve                  9459
Slider                 3366
Changeup              12014
Sinker                17194
Forkball              10894
Knuckle               18006
Other                 18013
누적_IP                     0
FIP                     527
GSv2                      0
avg_GSv2                  0
delta_GSv2                0
Total_IP                  0
직구_피안타율                   0
직구_구사율                    0
변화구_구사율                   0
dtype: int64

In [5]:
fatigue_df['WHIP'].unique()

array([ 0.83,  1.17,  1.83,  1.14,  1.33,  0.71,  0.75,  1.  ,  0.57,
        3.  ,  0.43,  1.5 ,  0.5 ,  0.78,  0.72,  0.63,  1.23,  0.29,
        1.67,  1.94,  2.06,  1.29,  0.86,  0.56,  2.36,  1.26,  1.43,
        1.6 ,  2.  ,  1.41,  3.21,  2.5 ,  1.05,  0.6 ,  3.5 ,  1.8 ,
        2.47,  2.6 ,  2.2 ,  1.11,  3.25,  2.14,  0.2 ,  0.  ,  1.2 ,
        4.5 ,  6.  ,   nan,  2.25,  9.  , 12.  ,  4.  ,  5.  ,  2.4 ,
        1.13,  3.86,  1.36, 10.  ,  0.33,  0.67,  1.4 ,  0.55,  1.76,
        1.42,  0.17,  1.62,  2.54,  0.95,  2.31,  4.13,  3.33,  1.75,
        1.31,  1.85,  2.45,  3.6 ,  3.27,  1.07,  7.5 ,  0.8 ,  1.91,
        2.67,  2.18,  2.75, 18.  ,  1.88,  1.15,  0.79,  3.75,  0.53,
        2.73,  1.25,  1.38,  1.71,  4.2 , 15.  ,  2.7 ,  3.38,  4.29,
        2.08,  1.24,  2.33,  0.4 ,  0.38,  1.64,  1.59,  5.25,  2.1 ,
        3.43,  0.92,  0.94,  0.82,  1.93,  1.09,  1.35,  1.69,  1.57,
        2.17,  2.57,  2.63,  7.  ,  0.47, 10.5 ,  3.67,  2.81,  0.3 ,
       24.  ,  0.27,  1.06,  3.3 ,  0.9 ,  7.8 ,  2.8 ,  1.58,  1.65,
        0.25,  2.12,  0.68,  1.89,  4.25,  2.79,  0.64,  0.69,  0.96,
        2.77,  2.29,  0.41,  0.91,  0.88,  1.74,  5.4 ,  0.45,  5.5 ,
        0.14,  0.65,  0.44,  0.39,  3.9 ,  0.52, 21.  ,  4.33,  8.  ,
        4.71,  5.14,  0.22,  5.57,  4.8 ,  3.55,  4.88,  0.46,  0.58,
        2.21,  1.04,  0.48,  6.5 ,  8.25,  0.15])

In [6]:
print(fatigue_df[fatigue_df['WHIP'].isna()])

      Name  Year Team        Date Role  ERA  WHIP   IP  NP  R  ...  Other  \
132    고효준  2022  SSG  2022-09-02   RP  0.0   NaN  0.0   4  0  ...    NaN
136    고효준  2022  SSG  2022-09-15   RP  0.0   NaN  0.0  12  1  ...    NaN
141    고효준  2022  SSG  2022-09-30   RP  0.0   NaN  0.0   4  0  ...    NaN
142    고효준  2022  SSG  2022-10-01   RP  0.0   NaN  0.0   7  1  ...    NaN
150    고효준  2023  SSG  2023-04-13   RP  0.0   NaN  0.0  11  2  ...    NaN
...    ...   ...  ...         ...  ...  ...   ...  ...  .. ..  ...    ...
17786  함덕주  2020   두산  2020-07-31   RP  0.0   NaN  0.0  13  3  ...    NaN
17800  함덕주  2023   LG  2023-04-09   RP  0.0   NaN  0.0   4  0  ...    NaN
17928  황동하  2023  KIA  2023-06-28   RP  0.0   NaN  0.0  10  2  ...    NaN
17974  황준서  2024   한화  2024-06-26   RP  0.0   NaN  0.0  10  3  ...    NaN
17993  황준서  2024   한화  2024-09-24   RP  0.0   NaN  0.0   8  0  ...    NaN

           누적_IP  FIP  GSv2   avg_GSv2  delta_GSv2   Total_IP  직구_피안타율  \
132    30.666667  NaN    39  43.866667   -4.866667  38.666667    0.255
136    33.333333  NaN    37  43.866667   -6.866667  38.666667    0.255
141    36.000000  NaN    40  43.866667   -3.866667  38.666667    0.255
142    36.000000  NaN    37  43.866667   -6.866667  38.666667    0.255
150     3.666667  NaN    33  43.369863  -10.369863  58.000000    0.178
...          ...  ...   ...        ...         ...        ...      ...
17786  28.000000  NaN    33  47.277778  -14.277778  55.333333    0.292
17800   4.666667  NaN    38  45.350877   -7.350877  55.666667    0.214
17928  12.333333  NaN    34  47.461538  -13.461538  31.333333    0.305
17974  53.666667  NaN    34  47.194444  -13.194444  72.000000    0.261
17993  71.666667  NaN    38  47.194444   -9.194444  72.000000    0.261

       직구_구사율  변화구_구사율
132      35.4     64.6
136      35.4     64.6
141      35.4     64.6
142      35.4     64.6
150      45.5     54.5
...       ...      ...
17786    56.6     43.4
17800    54.4     45.6
17928    50.0     50.0
17974    56.4     43.6
17993    56.4     43.6

[527 rows x 56 columns]

In [7]:
import numpy as np

# 마스크 정의
mask = (fatigue_df['IP'] == 0) & ((fatigue_df['H'] + fatigue_df['BB']) > 0)

# 결측 인디케이터터
fatigue_df['WHIP_missing_flag'] = fatigue_df['WHIP'].isna().astype(int)

# 할당 전 NaN 개수와 마스크 True 개수
before_nan = fatigue_df['WHIP'].isna().sum()
print("전체 NaN:", before_nan)
print("mask True 개수:", mask.sum())


#최대 WHIP 값(예: max_whip*2) 구하기
max_whip = fatigue_df.loc[fatigue_df['IP'] > 0, 'WHIP'].max()

# 할당 시도
fatigue_df.loc[mask, 'WHIP'] = max_whip * 2

# 할당 후 NaN 개수
after_nan = fatigue_df['WHIP'].isna().sum()
print("할당 후 NaN:", after_nan)

# 할당된 샘플 몇 개만 출력해서 WHIP 확인
print(fatigue_df.loc[mask, ['Year','Date','IP','H','BB','WHIP']].head(5))

전체 NaN: 527
mask True 개수: 508
할당 후 NaN: 19
     Year        Date   IP  H  BB  WHIP
132  2022  2022-09-02  0.0  1   0  48.0
136  2022  2022-09-15  0.0  1   1  48.0
142  2022  2022-10-01  0.0  2   0  48.0
150  2023  2023-04-13  0.0  1   1  48.0
165  2023  2023-05-24  0.0  1   1  48.0

In [8]:
# WHIP이 NaN인 행 드랍
fatigue_df = fatigue_df.dropna(subset=['WHIP']).copy()

# 확인: 결측 0개 되어야 함
print(fatigue_df['WHIP'].isna().sum())  # ➜ 0

0

In [9]:
fatigue_df

,Name,Year,Team,Date,Role,ERA,WHIP,IP,NP,R,...,누적_IP,FIP,GSv2,avg_GSv2,delta_GSv2,Total_IP,직구_피안타율,직구_구사율,변화구_구사율,WHIP_missing_flag
0,고영표,2021,KT,2021-04-07,SP,1.50,0.83,6.000000,88,1,...,6.000000,4.003,72,72.961538,-0.961538,166.666667,0.254000,28.0,72.0,0
1,고영표,2021,KT,2021-04-13,SP,4.50,1.17,6.000000,95,3,...,12.000000,1.337,72,72.961538,-0.961538,166.666667,0.254000,28.0,72.0,0
2,고영표,2021,KT,2021-04-18,SP,3.00,0.83,6.000000,91,2,...,18.000000,3.670,72,72.961538,-0.961538,166.666667,0.254000,28.0,72.0,0
3,고영표,2021,KT,2021-04-24,SP,4.50,1.83,6.000000,86,3,...,24.000000,2.503,64,72.961538,-8.961538,166.666667,0.254000,28.0,72.0,0
4,고영표,2021,KT,2021-04-30,SP,3.86,1.14,7.000000,97,3,...,31.000000,3.599,76,72.961538,3.038462,166.666667,0.254000,28.0,72.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18050,후라도,2024,키움,2024-08-25,SP,2.57,0.43,7.000000,101,2,...,165.333333,4.023,80,71.766667,8.233333,190.333333,0.291414,53.6,46.4,0
18051,후라도,2024,키움,2024-09-03,SP,5.79,1.93,4.666667,103,7,...,170.000000,5.095,59,71.766667,-12.766667,190.333333,0.291414,53.6,46.4,0
18052,후라도,2024,키움,2024-09-08,SP,3.68,0.95,7.333333,97,4,...,177.333333,2.075,78,71.766667,6.233333,190.333333,0.291414,53.6,46.4,0
18053,후라도,2024,키움,2024-09-14,SP,1.29,1.00,7.000000,90,1,...,184.333333,4.309,75,71.766667,3.233333,190.333333,0.291414,53.6,46.4,0
18054,후라도,2024,키움,2024-09-22,SP,9.00,1.00,6.000000,88,6,...,190.333333,9.333,61,71.766667,-10.766667,190.333333,0.291414,53.6,46.4,0

In [10]:
# 결과를 CSV로 저장
fatigue_df.to_csv("../data/processed/피로도_보간완료.csv", index=False, encoding="utf-8-sig")